apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml
- secret.yaml

# For local testing, we might want to expose it via NodePort
patches:
- target:
    kind: Service
    name: cloudscale-api
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 30000
