apiVersion: v1
kind: Secret
metadata:
  name: cloudscale-secrets
type: Opaque
stringData:
  # Using host.docker.internal to reach the docker-compose postgres from within local k8s (e.g. Docker Desktop)
  DATABASE_URL: "postgresql://user:password@host.docker.internal:5432/taskdb?schema=public"
