apiVersion: v1
kind: Service
metadata:
  name: cloudscale-api
  labels:
    app: cloudscale-api
spec:
  selector:
    app: cloudscale-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
